import * as dotenv from 'dotenv';
dotenv.config();

const environments = {
  ENVIRONMENT: process.env.ENVIRONMENT,
  NETWORK_ID: process.env.NETWORK_ID,
  ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY,
  OPENSEA_API_KEY: process.env.OPENSEA_API_KEY,
  PRIVY_APP_ID: process.env.PRIVY_APP_ID,
  PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
  UNISWAP_CONTRACT_ADDRESS: process.env.UNISWAP_CONTRACT_ADDRESS,
  SIGNER_WALLET_PRIVATE_KEY: process.env.SIGNER_WALLET_PRIVATE_KEY,
  SIGNER_ADDRESS: process.env.SIGNER_ADDRESS,
  CRON_CALCULATE_WORKER_BUILDING_PRICE: process.env.CRON_CALCULATE_WORKER_BUILDING_PRICE,
  CRON_UPDATE_FIAT_PRICE: process.env.CRON_UPDATE_FIAT_PRICE,
  CRON_UPDATE_NFT_PRICE: process.env.CRON_UPDATE_NFT_PRICE,
  CRON_ESTIMATE_GAS_PRICE: process.env.CRON_ESTIMATE_GAS_PRICE,
  CRON_GET_ETH_PRICE: process.env.CRON_GET_ETH_PRICE,
};

export default environments;
