import * as dotenv from 'dotenv';
dotenv.config();

const environments = {
  ENVIRONMENT: process.env.ENVIRONMENT,
  NETWORK_ID: process.env.NETWORK_ID,
  QUICKNODE_API_ENDPOINT: process.env.QUICKNODE_API_ENDPOINT,
  OPENSEA_API_KEY: process.env.OPENSEA_API_KEY,
  PRIVY_APP_ID: process.env.PRIVY_APP_ID,
  PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
  UNISWAP_CONTRACT_ADDRESS: process.env.UNISWAP_CONTRACT_ADDRESS,
  SIGNER_WALLET_PRIVATE_KEY: process.env.SIGNER_WALLET_PRIVATE_KEY,
  MARKETING_WALLET_PRIVATE_KEY: process.env.MARKETING_WALLET_PRIVATE_KEY,
  SIGNER_ADDRESS: process.env.SIGNER_ADDRESS,
  CRON_CALCULATE_WORKER_BUILDING_PRICE: process.env.CRON_CALCULATE_WORKER_BUILDING_PRICE,
  CRON_UPDATE_FIAT_PRICE: process.env.CRON_UPDATE_FIAT_PRICE,
  CRON_UPDATE_NFT_PRICE: process.env.CRON_UPDATE_NFT_PRICE,
  CRON_ESTIMATE_GAS_PRICE: process.env.CRON_ESTIMATE_GAS_PRICE,
  CRON_GET_ETH_PRICE: process.env.CRON_GET_ETH_PRICE,
  CRON_BURN_FIAT: process.env.CRON_BURN_FIAT,
  CRON_EXTRACT_USER: process.env.CRON_EXTRACT_USER,
  CRON_CALCULATE_TXN_PRICE: process.env.CRON_CALCULATE_TXN_PRICE,
  CRON_INCREASE_SPIN: process.env.CRON_INCREASE_SPIN,
  CRON_UPDATE_BLAST_POINTS: process.env.CRON_UPDATE_BLAST_POINTS,
  CRON_UPDATE_U_POINTS: process.env.CRON_UPDATE_U_POINTS,
  BLAST_OPERATOR_ADDRESS: process.env.BLAST_OPERATOR_ADDRESS,
  BLAST_OPERATOR_PRIVATE_KEY: process.env.BLAST_OPERATOR_PRIVATE_KEY,
  BLAST_API_URL: process.env.BLAST_API_URL,
};

export default environments;
