import * as dotenv from 'dotenv';
dotenv.config();

const environments = {
  ENVIRONMENT: process.env.ENVIRONMENT,
  PORT: process.env.PORT,
  NETWORK_ID: process.env.NETWORK_ID,
  PRIVY_APP_ID: process.env.PRIVY_APP_ID,
  PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
  PRIVY_VERIFICATION_KEY: process.env.PRIVY_VERIFICATION_KEY,
  QUICKNODE_API_ENDPOINT: process.env.QUICKNODE_API_ENDPOINT,
  WORKER_WALLET_PRIVATE_KEY: process.env.WORKER_WALLET_PRIVATE_KEY,
  SIGNER_WALLET_PRIVATE_KEY: process.env.SIGNER_WALLET_PRIVATE_KEY,
  SYSTEM_ADDRESS: process.env.SYSTEM_ADDRESS,
  CRON_GANG_WAR: process.env.CRON_GANG_WAR,
  TWITTER_CONSUMER_API_KEY: process.env.TWITTER_CONSUMER_API_KEY,
  TWITTER_CONSUMER_API_SECRET: process.env.TWITTER_CONSUMER_API_SECRET,
  TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
  TWITTER_BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN,
  TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET,
  SITE_URL: process.env.SITE_URL,
};

export default environments;
