const environments = {
  FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
  API_URL: process.env.REACT_APP_API_URL,
  PRIVY_APP_ID: process.env.REACT_APP_PRIVY_APP_ID,
  NETWORK_ID: process.env.REACT_APP_NETWORK_ID,
  GAME_CONTRACT_ADDRESS: process.env.REACT_APP_GAME_CONTRACT_ADDRESS,
  TOKEN_ADDRESS: process.env.REACT_APP_TOKEN_ADDRESS,
  NFT_ADDRESS: process.env.REACT_APP_NFT_ADDRESS,
  SYSTEM_ADDRESS: process.env.REACT_APP_SYSTEM_ADDRESS,
};

export default environments;
